using AutoMapper;
using System;
using System.Linq;
using System.Web.Http;
using Vidly2.Dtos;
using Vidly2.Models;
using System.Data.Entity;
using System.Collections.Generic;

namespace Vidly2.Controllers.Api
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/movies
        public IEnumerable<MovieDto> GetMovies(string query = null)
        {

            var moviesQuery = _context.Movies
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));

            return moviesQuery.ToList().Select(Mapper.Map<Movie, MovieDto>);

        }

        ////GET /api/movies
        //public IEnumerable<MovieDto> GetMovies()
        //{
        //    return _context.Movies
        //        .Include(m => m.Genre)
        //        .ToList()
        //        .Select(Mapper.Map<Movie, MovieDto>);
        //}

        //GET /api/movies/1
        [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult GetMovies(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();

            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }

        //POST /api/movies
        [HttpPost]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult CreateMovie (MovieDto movieDto)
        {
            if(!ModelState.IsValid)
            {
                return BadRequest();
            }

            var movieInDb = Mapper.Map<MovieDto, Movie>(movieDto);

            _context.Movies.Add(movieInDb);
            _context.SaveChanges();

            //This customer object has an ID that is generated by the DB
            //so we want to add this ID in our DTO and return it to the client.
            movieDto.Id = movieInDb.Id;

            //Here, as a part of RESTful convention, we need to return the URI 
            //of the newly created resource to the client,like "api/movie/10"
            //This also returns 201 Created isntead of 200 OK.
            return Created(new Uri(Request.RequestUri + "/" + movieInDb.Id), movieDto);
        }

        [HttpPut]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                return NotFound();

            Mapper.Map(movieDto, movieInDb);

            _context.SaveChanges();

            return Ok();
        }

        [HttpDelete]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                return NotFound();

            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();

            return Ok();

        }
    }
}
